project:
  type: website
  preview: 
    port: 4200
  output-dir: docs  
lang: en
language: 
  title-block-author-single: "Author"
website:
  title: "Ismaila Ouedraogo"
  page-navigation: false
  site-url: "https://ismo168.github.io/blog/"
  description: "Bienvenue sur mon site personnel. Je suis Ouedraogo, un passionné de la data science et ses applications business à forte value ajoutée. Explorez mes projets, articles de blog et plus encore !"
  
  page-footer:
    left: '<p>Copyright &copy; <script>document.write(new Date().getFullYear())</script> Boukary Ouedraogo</p>'
    center: "Powered by ❤️, [Quarto](https://quarto.org/) et <img width='20' height='20' src='https://img.icons8.com/fluency/48/r-project.png' alt='r-project'/>"
    right:
      - icon: github
        href: https://github.com/ismo168 
      - icon: linkedin
        href: https://www.linkedin.com/in/ismaila-ouedraogo/
      - icon: envelope
        href: mailto:ouedraogoismaila4@gmail.com
  
  
  navbar:
    pinned: true
    right:
      - href: index.qmd
        text: Home
        
      - href: about.qmd
        text: About me
        
      - text: Publications
        href: posts/posts.qmd
      
        
format:
  html:
    theme: [pulse, custom.scss]
    include-before-body: assets/include-before-body.html
    include-after-body: assets/projects.html  # Inclure le fichier JavaScript
    
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.ouedraogo-boukary\.com\/**'
    citations-hover: true
    footnotes-hover: true
    toc: false
    code-link: true
execute:
  freeze: auto
resources:
  - assets/**
